#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("formatEvent() works", {

  expect_error(
    kwb.monitoring:::formatEvent()
    # argument "event" is missing, with no default
  )

})

