#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("plotRemovedIntervals() works", {

  expect_error(
    kwb.monitoring:::plotRemovedIntervals()
    # argument "removedIntervals" is missing, with no default
  )

})

