#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("H_above_threshold() works", {

  expect_error(
    kwb.monitoring:::H_above_threshold()
    # argument "dat.raw" is missing, with no default
  )

})

