#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("sampleDataToSamplingEvents() works", {

  expect_error(
    kwb.monitoring:::sampleDataToSamplingEvents()
    # argument "sampleData" is missing, with no default
  )

})

