#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("formatBottleEnumeration() works", {

  expect_error(
    kwb.monitoring:::formatBottleEnumeration()
    # argument "bottles" is missing, with no default
  )

})

