#
# This test file has been generated by kwb.test::create_test_files()
#

test_that(".drawLimits() works", {

  expect_error(
    kwb.monitoring:::.drawLimits()
    # argument "v" is missing, with no default
  )

})

