#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("getAllTypesOfEvents() works", {

  expect_error(
    kwb.monitoring:::getAllTypesOfEvents()
    # argument "settings" is missing, with no default
  )

})

