#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("plotOverview_total() works", {

  expect_error(
    kwb.monitoring:::plotOverview_total()
    # argument "dat" is missing, with no default
  )

})

