#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("whichAboveThresholds() works", {

  expect_error(
    kwb.monitoring:::whichAboveThresholds()
    # argument "hydraulicData" is missing, with no default
  )

})

