#
# This test file has been generated by kwb.test::create_test_files()
#

test_that(".getRainXLims() works", {

  expect_error(
    kwb.monitoring:::.getRainXLims()
    # argument "gauges" is missing, with no default
  )

})

