#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("formatDuration() works", {

  expect_error(
    kwb.monitoring:::formatDuration()
    # argument "duration.s" is missing, with no default
  )

})

