#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("plotSampleInformation() works", {

  expect_error(
    kwb.monitoring:::plotSampleInformation()
    # argument "sampleInformation" is missing, with no default
  )

})

