#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("plot_H_v_Q() works", {

  expect_error(
    kwb.monitoring:::plot_H_v_Q()
    # could not find function "plot_variable"
  )

})

