#
# This test file has been generated by kwb.test::create_test_files()
#

test_that(".getXLim() works", {

  expect_error(
    kwb.monitoring:::.getXLim()
    # argument "timestamps" is missing, with no default
  )

})

