#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("get_H_threshold() works", {

  expect_error(
    kwb.monitoring:::get_H_threshold()
    # argument "settings" is missing, with no default
  )

})

