#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("findUniqueTimeStepOrStop() works", {

  expect_error(
    kwb.monitoring:::findUniqueTimeStepOrStop()
    # argument "timeStamps" is missing, with no default
  )

})

