#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("getLimitsFromHistoryOrDefault() works", {

  expect_error(
    kwb.monitoring:::getLimitsFromHistoryOrDefault()
    # argument "regressionState" is missing, with no default
  )

})

