#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("formatEventStatisticsTable() works", {

  expect_error(
    kwb.monitoring:::formatEventStatisticsTable()
    # argument "eventStatisticsExtended" is missing, with no default
  )

})

