#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("availableAutoSamplerFiles2() works", {

  expect_error(
    kwb.monitoring:::availableAutoSamplerFiles2()
    # argument "dictionaryFile" is missing, with no default
  )

})

