#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("appendColumn_samplesOk() works", {

  expect_error(
    kwb.monitoring:::appendColumn_samplesOk()
    # argument "samplingEvents" is missing, with no default
  )

})

