#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("saveRegressionModel() works", {

  expect_error(
    kwb.monitoring:::saveRegressionModel()
    # settings is not a list but:
#  NULL
  )

})

