#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("removeDuplicates() works", {

  expect_error(
    kwb.monitoring:::removeDuplicates()
    # argument "hydraulicData" is missing, with no default
  )

})

