#
# This test file has been generated by kwb.test::create_test_files()
#

test_that(".textplot_eventInfo() works", {

  expect_error(
    kwb.monitoring:::.textplot_eventInfo()
    # argument "settings" is missing, with no default
  )

})

