#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("appendInterpolColumns() works", {

  expect_error(
    kwb.monitoring:::appendInterpolColumns()
    # argument "hydraulicData" is missing, with no default
  )

})

