#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("pathDictionary() works", {

  expect_error(
    kwb.monitoring:::pathDictionary()
    # argument "dictionaryFile" is missing, with no default
  )

})

