#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("plot_hydraulic_events() works", {

  expect_error(
    kwb.monitoring:::plot_hydraulic_events()
    # argument "eventsAndStat" is missing, with no default
  )

})

