#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("getFunctionValueOrDefault2() works", {

  expect_error(
    kwb.monitoring:::getFunctionValueOrDefault2()
    # argument "default" is missing, with no default
  )

})

