#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("plot_Q_columns() works", {

  expect_error(
    kwb.monitoring:::plot_Q_columns()
    # argument "hydraulicData" is missing, with no default
  )

})

