#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("readAndJoinSamplerFiles() works", {

  expect_error(
    kwb.monitoring:::readAndJoinSamplerFiles()
    # argument "samplerFiles" is missing, with no default
  )

})

