#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("plotOverview_byDay() works", {

  expect_error(
    kwb.monitoring:::plotOverview_byDay()
    # argument "dat" is missing, with no default
  )

})

