#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("getOrCreatePath() works", {

  expect_error(
    kwb.monitoring:::getOrCreatePath()
    # argument "variableName" is missing, with no default
  )

})

