#
# This test file has been generated by kwb.test::create_test_files()
#

test_that(".getRainLimits() works", {

  expect_error(
    kwb.monitoring:::.getRainLimits()
    # argument "values" is missing, with no default
  )

})

