#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("availableAutoSamplerFiles() works", {

  expect_error(
    kwb.monitoring:::availableAutoSamplerFiles()
    # There is no folder "SAMPLE_DIR"!
  )

})

