#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("apply_H_threshold() works", {

  expect_error(
    kwb.monitoring:::apply_H_threshold()
    # argument "dat.raw" is missing, with no default
  )

})

