#
# This test file has been generated by kwb.test::create_test_files()
#

test_that(".getResultColours() works", {

  expect_error(
    kwb.monitoring:::.getResultColours()
    # argument "resultTypes" is missing, with no default
  )

})

