#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("addSampleTimesToPlot() works", {

  expect_error(
    kwb.monitoring:::addSampleTimesToPlot()
    # argument "sampleTimes" is missing, with no default
  )

})

