#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("formatEventRelation() works", {

  expect_error(
    kwb.monitoring:::formatEventRelation()
    # argument "mergedEventAndStat" is missing, with no default
  )

})

