#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("formatSettings() works", {

  expect_error(
    kwb.monitoring:::formatSettings()
    # argument "settings" is missing, with no default
  )

})

