#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("calculateVolumeCompositeSample() works", {

  expect_error(
    kwb.monitoring:::calculateVolumeCompositeSample()
    # argument "hydraulicSubset" is missing, with no default
  )

})

