#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("getStatisticsByDay() works", {

  expect_error(
    kwb.monitoring:::getStatisticsByDay()
    # argument "dataFrame" is missing, with no default
  )

})

