#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("formatDurationDaysHours() works", {

  expect_error(
    kwb.monitoring:::formatDurationDaysHours()
    # argument "duration.h" is missing, with no default
  )

})

