#
# This test file has been generated by kwb.test::create_test_files()
#

test_that(".drawAdditionalThresholdsIfApplicable() works", {

  expect_error(
    kwb.monitoring:::.drawAdditionalThresholdsIfApplicable()
    # argument "time.dependent.thresholds" is missing, with no default
  )

})

