#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("formatVolumeCompositeSample() works", {

  expect_error(
    kwb.monitoring:::formatVolumeCompositeSample()
    # argument "volumeCompositeSample" is missing, with no default
  )

})

