#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("addZoomToHistory() works", {

  expect_error(
    kwb.monitoring:::addZoomToHistory()
    # argument "zoomHistory" is missing, with no default
  )

})

