#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("plot_hydraulic_event() works", {

  expect_error(
    kwb.monitoring:::plot_hydraulic_event()
    # argument "eventAndStat" is missing, with no default
  )

})

