#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("indicesInIntervals() works", {

  expect_error(
    kwb.monitoring:::indicesInIntervals()
    # argument "intervals" is missing, with no default
  )

})

