#
# This test file has been generated by kwb.test::create_test_files()
#

test_that(".partialPlot_Q() works", {

  expect_error(
    kwb.monitoring:::.partialPlot_Q()
    # argument "settings" is missing, with no default
  )

})

