#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("getLegendTextWithNaInfo() works", {

  expect_error(
    kwb.monitoring:::getLegendTextWithNaInfo()
    # argument "selection" is missing, with no default
  )

})

