#
# This test file has been generated by kwb.test::create_test_files()
#

test_that(".getShadingLinesDensities() works", {

  expect_error(
    kwb.monitoring:::.getShadingLinesDensities()
    # argument "bottleNumbers" is missing, with no default
  )

})

