#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("filterForRelevantBottles() works", {

  expect_error(
    kwb.monitoring:::filterForRelevantBottles()
    # argument "sampleDataExtended" is missing, with no default
  )

})

