#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("plot_H_vs_Q() works", {

  expect_error(
    kwb.monitoring:::plot_H_vs_Q()
    # argument "selection" is missing, with no default
  )

})

