#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("getRemovedIntervals() works", {

  expect_error(
    kwb.monitoring:::getRemovedIntervals()
    # argument "used" is missing, with no default
  )

})

