#
# This test file has been generated by kwb.test::create_test_files()
#

test_that(".addFakeEntriesForDaysWithoutData() works", {

  expect_error(
    kwb.monitoring:::.addFakeEntriesForDaysWithoutData()
    # argument "dataFrame" is missing, with no default
  )

})

