#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("selectIntervalsForCorrelation() works", {

  expect_error(
    kwb.monitoring:::selectIntervalsForCorrelation()
    # argument "dat.all" is missing, with no default
  )

})

