#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("formatEventStatistics() works", {

  expect_error(
    kwb.monitoring:::formatEventStatistics()
    # argument "eventStatistics" is missing, with no default
  )

})

