#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("showOverview() works", {

  expect_error(
    kwb.monitoring:::showOverview()
    # argument "dat" is missing, with no default
  )

})

