#
# This test file has been generated by kwb.test::create_test_files()
#

test_that(".replace_NA_with_zero_and_warn() works", {

  expect_error(
    kwb.monitoring:::.replace_NA_with_zero_and_warn()
    # argument "H" is missing, with no default
  )

})

