#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("setPausesOfMergedEvents() works", {

  expect_error(
    kwb.monitoring:::setPausesOfMergedEvents()
    # argument "mergedEvents" is missing, with no default
  )

})

