#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("samplingEventsToBottleEvents() works", {

  expect_error(
    kwb.monitoring:::samplingEventsToBottleEvents()
    # argument "samplingEvents" is missing, with no default
  )

})

