#
# This test file has been generated by kwb.test::create_test_files()
#

test_that(".setPageLayout() works", {

  expect_error(
    kwb.monitoring:::.setPageLayout()
    # argument "numberOfGauges" is missing, with no default
  )

})

