#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("mergeParallelRainEventStat() works", {

  expect_error(
    kwb.monitoring:::mergeParallelRainEventStat()
    # argument "hydraulicEvents" is missing, with no default
  )

})

