#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("bottleEventsToSamplerEvents() works", {

  expect_error(
    kwb.monitoring:::bottleEventsToSamplerEvents()
    # argument "bottleEvents" is missing, with no default
  )

})

