#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("getModelFromFile() works", {

  expect_error(
    kwb.monitoring:::getModelFromFile()
    # argument "modelFile" is missing, with no default
  )

})

