#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("getAllSamplerEvents() works", {

  expect_error(
    kwb.monitoring:::getAllSamplerEvents()
    # argument "stations" is missing, with no default
  )

})

