#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("filterSampleEventsForFilename() works", {

  expect_error(
    kwb.monitoring:::filterSampleEventsForFilename()
    # argument "events" is missing, with no default
  )

})

