#
# This test file has been generated by kwb.test::create_test_files()
#

test_that(".getThresholdOrStop() works", {

  expect_error(
    kwb.monitoring:::.getThresholdOrStop()
    # argument "thresholds" is missing, with no default
  )

})

