#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("configure() works", {

  expect_error(
    kwb.monitoring:::configure()
    # argument "rawdir" is missing, with no default
  )

})

