#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("dateToDateStringInPath() works", {

  expect_error(
    kwb.monitoring:::dateToDateStringInPath()
    # argument "x" is missing, with no default
  )

})

