#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("updateZoomHistory() works", {

  expect_error(
    kwb.monitoring:::updateZoomHistory()
    # argument "action" is missing, with no default
  )

})

