#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("plot_sampled_event() works", {

  expect_error(
    kwb.monitoring:::plot_sampled_event()
    # length(samplerFile) == 1 is not TRUE
  )

})

