#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("getAllSamplerEventsFromFiles() works", {

  expect_error(
    kwb.monitoring:::getAllSamplerEventsFromFiles()
    # argument "samplerFiles" is missing, with no default
  )

})

