#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("plotEventDistribution() works", {

  expect_error(
    kwb.monitoring:::plotEventDistribution()
    # argument "settings" is missing, with no default
  )

})

