#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("sampleLogFileToSampleName() works", {

  expect_error(
    kwb.monitoring:::sampleLogFileToSampleName()
    # argument "sampleFile" is missing, with no default
  )

})

