#
# This test file has been generated by kwb.test::create_test_files()
#

test_that(".maxValue_to_lim() works", {

  expect_error(
    kwb.monitoring:::.maxValue_to_lim()
    # argument "maxValue" is missing, with no default
  )

})

