#
# This test file has been generated by kwb.test::create_test_files()
#

test_that(".getYLim() works", {

  expect_error(
    kwb.monitoring:::.getYLim()
    # argument "gaugeIndices" is missing, with no default
  )

})

