#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("writeCsvToPathFromDictionary() works", {

  expect_error(
    kwb.monitoring:::writeCsvToPathFromDictionary()
    # argument "key" is missing, with no default
  )

})

