#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("plotTotalDischargeVersusRainProperties() works", {

  expect_error(
    kwb.monitoring:::plotTotalDischargeVersusRainProperties()
    # argument "stations" is missing, with no default
  )

})

