#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("saveSampleInformation() works", {

  expect_error(
    kwb.monitoring:::saveSampleInformation()
    # argument "sampleFile" is missing, with no default
  )

})

